#!/bin/bash
git config --global user.name "Blixa Morgan"
git config --global user.email "blixa@projectmakeit.com"
if [ "$GITINIT" ]; then
	echo "Generating a new git repo.";
	initGit;
else
	echo "Cloning from $GITREPO.";
	cloneGit;
fi
if [ -f "package.json" ]; then
	activate node
fi
if [ -f "require.txt" ]; then
	activate python
fi
